import type { Profile } from "./types.ts";

export const YCARO_PROFILE: Profile = {
  name: "Ycaro Pires",
  email: "ycaro.oleg.job@gmail.com",
  phone: "++1-555-0032",
  city: "Fortaleza",
  country: "Brazil",
  linkedinUrl: "https://www.linkedin.com/in/ycaro-pires-944297240/",
  githubUrl: "https://github.com/Ycaro-Oleg",
  websiteUrl: "https://ycaro-oleg.github.io/",
  currentTitle: "Mid-level Software Engineer",
  currentCompany: "Coreplan",
  yearsExperience: 4,
  yearsRuby: 4,
  yearsRails: 4,
  noticePeriodDays: null,
  salaryTarget: "",
  basedIn: "BR",
  needsUsSponsorship: true,
  availableAs: ["contractor", "eor"],
  skills: [
    "Ruby",
    "Ruby on Rails",
    "Rails",
    "PostgreSQL",
    "SQL",
    "Sidekiq",
    "JavaScript",
    "React",
    "Next.js",
    "REST API",
    "CI/CD",
    "RSpec",
    "Node.js",
  ],
  targetTitles: [
    "Backend Engineer",
    "Backend Developer",
    "Rails Engineer",
    "Ruby Developer",
    "Software Engineer",
    "Full Stack Engineer",
  ],
  targetKeywords: ["backend engineer", "ruby", "rails", "remote", "full stack"],
  answers: {
    firstName: "Ycaro",
    lastName: "Pires",
    fullName: "Ycaro Pires",
    email: "ycaro.oleg.job@gmail.com",
    phone: "++1-555-0032",
    city: "Fortaleza",
    country: "Brazil",
    linkedin: "https://www.linkedin.com/in/ycaro-pires-944297240/",
    github: "https://github.com/Ycaro-Oleg",
    website: "https://ycaro-oleg.github.io/",
    currentCompany: "Coreplan",
    currentTitle: "Mid-level Software Engineer",
    yearsExperience: "4",
    yearsRuby: "4",
    yearsRails: "4",
    needsSponsorship: "Yes, for a US employee role",
    sponsorshipExplanation:
      "I am based in Brazil. I would need sponsorship for a US employee role. I am available to work remotely as a contractor or via EOR (Deel and similar).",
    willingToRelocate: "No. Remote from Brazil.",
    rightToWorkEu: "No. Remote contractor / EOR only.",
    howHeard: "Company careers page",
    startDate: "After notice period",
    demographics: "decline",
  },
  resume: {
    summary:
      "Backend Software Engineer with experience building scalable, high-availability systems using Ruby on Rails in production. Mission-critical integrations for public-sector clients, API-driven services, background jobs, CI/CD, and AI-powered workflows via external APIs.",
    skills: [
      "Ruby",
      "Ruby on Rails",
      "PostgreSQL",
      "Sidekiq",
      "JavaScript",
      "React",
      "Next.js",
      "REST API",
      "CI/CD",
      "RSpec",
    ],
    experience: [
      {
        id: "coreplan-mid",
        company: "Coreplan",
        title: "Mid-level Software Engineer",
        start: "2024-04",
        end: "present",
        bullets: [
          {
            id: "dje",
            text: "Drove end-to-end design and delivery of a mission-critical DJE (Diario da Justica Eletronico) REST integration, opening an official judicial communication channel adopted across 4+ State Attorney General Offices.",
            keywords: ["api", "rest", "integration", "rails"],
          },
          {
            id: "speed",
            text: "Improved data traceability and legal communication delivery speed by ~40% through structured flow orchestration and error handling.",
            keywords: ["reliability", "performance"],
          },
          {
            id: "incidents",
            text: "Identified system bottlenecks and proposed architectural improvements that reduced production incidents by ~25%.",
            keywords: ["architecture", "reliability"],
          },
          {
            id: "ai",
            text: "Integrated an AI-powered solution via external APIs — flow orchestration, data processing, and response validation — alongside CI/CD-driven deployments.",
            keywords: ["ai", "api", "ci/cd"],
          },
        ],
      },
      {
        id: "coreplan-jr",
        company: "Coreplan",
        title: "Junior Software Developer",
        start: "2023-04",
        end: "2024-04",
        bullets: [
          {
            id: "states",
            text: "Shipped features for 4 State Attorney General Offices (Mato Grosso, Distrito Federal, Espirito Santo, Maranhao) on Ruby on Rails, JavaScript, and PostgreSQL.",
            keywords: ["rails", "postgresql", "javascript"],
          },
          {
            id: "portal",
            text: "Built the Conciliation Portal frontend with React.js and Next.js in a microservices architecture.",
            keywords: ["react", "nextjs", "frontend"],
          },
        ],
      },
    ],
    education: [
      {
        school: "University Estacio de Sa",
        degree: "B.S. in Systems Analysis and Development",
        end: "2025-07",
        gpa: "3.7 / 4.0",
      },
    ],
    projects: [
      {
        name: "Kaerus",
        url: "https://kaerus.dev/",
        text: "Debugging assessment platform with deterministic incident simulations and sandboxed graders.",
      },
      {
        name: "Verdikt",
        url: "https://github.com/Ycaro-Oleg/Verdikt",
        text: "AI-powered purchase advisor. Rails 8, PostgreSQL, Sidekiq, Claude API.",
      },
    ],
    languages: [
      { name: "Portuguese", level: "Native" },
      { name: "English", level: "Fluent" },
      { name: "Spanish", level: "Basic" },
    ],
  },
};
