import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const profiles = sqliteTable("profiles", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull().default(""),
  city: text("city").notNull().default(""),
  country: text("country").notNull().default(""),
  linkedinUrl: text("linkedin_url").notNull().default(""),
  githubUrl: text("github_url").notNull().default(""),
  websiteUrl: text("website_url").notNull().default(""),
  currentTitle: text("current_title").notNull().default(""),
  currentCompany: text("current_company").notNull().default(""),
  yearsExperience: integer("years_experience").notNull().default(0),
  yearsRuby: integer("years_ruby").notNull().default(0),
  yearsRails: integer("years_rails").notNull().default(0),
  noticePeriodDays: integer("notice_period_days"),
  salaryTarget: text("salary_target").notNull().default(""),
  basedIn: text("based_in").notNull().default("BR"),
  needsUsSponsorship: integer("needs_us_sponsorship", { mode: "boolean" }).notNull().default(true),
  availableAs: text("available_as").notNull().default("[]"),
  skills: text("skills").notNull().default("[]"),
  targetTitles: text("target_titles").notNull().default("[]"),
  targetKeywords: text("target_keywords").notNull().default("[]"),
  answers: text("answers").notNull().default("{}"),
  resume: text("resume").notNull().default("{}"),
  resumePdfPath: text("resume_pdf_path"),
  updatedAt: text("updated_at").notNull(),
});

export const companyBoards = sqliteTable(
  "company_boards",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    ats: text("ats").notNull(),
    slug: text("slug").notNull(),
    kind: text("kind").notNull(),
    active: integer("active", { mode: "boolean" }).notNull().default(true),
    locationHint: text("location_hint").notNull().default(""),
    lastFetchedAt: text("last_fetched_at"),
    lastError: text("last_error"),
  },
  (t) => [uniqueIndex("boards_ats_slug").on(t.ats, t.slug)],
);

export const jobs = sqliteTable(
  "jobs",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    companyBoardId: integer("company_board_id").notNull(),
    externalId: text("external_id").notNull(),
    ats: text("ats").notNull(),
    company: text("company").notNull(),
    title: text("title").notNull(),
    location: text("location").notNull().default(""),
    remote: integer("remote", { mode: "boolean" }).notNull().default(false),
    url: text("url").notNull(),
    applyUrl: text("apply_url").notNull(),
    description: text("description").notNull().default(""),
    postedAt: text("posted_at"),
    region: text("region").notNull().default("other"),
    hiringGeo: text("hiring_geo").notNull().default("unknown"),
    roleFit: text("role_fit").notNull().default("no"),
    score: real("score").notNull().default(0),
    status: text("status").notNull().default("new"),
    queuedOn: text("queued_on"),
    coverLetter: text("cover_letter"),
    whyThisCompany: text("why_this_company"),
    tailoredResumeJson: text("tailored_resume_json"),
    tailoredResumePdfPath: text("tailored_resume_pdf_path"),
    appliedAt: text("applied_at"),
    notes: text("notes"),
  },
  (t) => [uniqueIndex("jobs_board_external").on(t.companyBoardId, t.externalId)],
);
